sudo: required
services:
   - docker

before_install:
   - docker build -t marcusblankenship/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true marcusblankenship/docker-react npm run test 
